project: libBlocksRuntime
version: 0.1

libraries:
    libBlocksRuntime:
        abi_major: 0
        abi_minor: 0
        cflags: "-DBlocksRuntime_EXPORTS -DHAVE_SYNC_BOOL_COMPARE_AND_SWAP_INT -DHAVE_SYNC_BOOL_COMPARE_AND_SWAP_LONG -std=c99 -Wall -Wextra -W -pedantic -Wno-unused-parameter"
        sources: [ runtime.c, data.c ]
        headers: [ Block.h, Block_private.h ]

package:
    summary: "Blocks Runtime library"
    description: "Blocks Runtime library"
    license: LLVM
    author: "LLVM Development Team"
