project: libBlocksRuntime
version: 0.1

headers:
    Block.h: '$(INCLUDEDIR)'
    Block_private.h: '$(INCLUDEDIR)'

libraries:
    libBlocksRuntime:
        abi_major: 0
        abi_minor: 0
        cflags: "-DBlocksRuntime_EXPORTS -DHAVE_SYNC_BOOL_COMPARE_AND_SWAP_INT=1 -DHAVE_SYNC_BOOL_COMPARE_AND_SWAP_LONG=1 -std=c99 -Wall -Wextra -W -pedantic -Wno-unused-parameter"
        sources: [ runtime.c, data.c ]

package:
    summary: "Blocks Runtime library"
    description: "Blocks Runtime library"
    license: LLVM
    author: "LLVM Development Team"
